spring:
  application.name: multithreadloader-migrator
  datasource:
    password: temp_db
    url: jdbc:postgresql://localhost:5432/temp_db
    username: temp_db
management:
  server:
    port: 8091
server:
  port: 8081